DROP TABLE IF EXISTS task_categories;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS priority;
DROP TYPE IF EXISTS status;
